config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  scope :api do
    delete 'todos_done' => 'todos#destroy_all_done'
    delete 'todos/:id' => 'todos#destroy'
    delete 'todos_all' => 'todos#destroy_all'
    get 'todos(.:format)' => 'todos#index'
    get 'todos/:id(.:format)' => 'todos#show'
    put 'todos/:id(.:format)' => 'todos#update'
    post 'todos(.:format)' => 'todos#create' 
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :title, presence: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

skip_before_filter :verify_authenticity_token

  def update
    @todo = Todo.find(params[:id])
    if @todo.update(todo_params)
      render json: @todo, status: :ok
    else
      render json: @todo.errors, status: :unprocessable_entity
    end
  end
  
  def create
     
      @todo = Todo.new(todo_params)
        if !@todo.save
          render json: @todo.errors, status: :unprocessable_entity
        else
          render json: @todo, status: :ok
        end      
  end
  
  def new
    @todo = Todo.new
  end
  
  def index
    render json: Todo.all
  end
  
  def show  
    render nothing: true and return if !Todo.exists?(params[:id]) 
    render json: Todo.find(params[:id])
  end
  
  def destroy_all_done
    Todo.where(:done => true).destroy_all
     render json: {status: :ok}     
  end
  
  def destroy
    @todo = Todo.find(params[:id])
      if !@todo.destroy
        render json: @todo.errors, status: :unprocessable_entity
      else
        render json: {status: :ok}
      end
  end
  
  def destroy_all
    Todo.destroy_all
    render json: {status: :ok}
  end
  
  def new
    @todo = Todo.new
  end
  

  def toggle_done
    toggle(:done)
  end
  
   def todo_params
    params.require(:todo).permit(:done, :title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="todoApp" ng-strict-di>
<head>
	<title>ToDo</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
 
	<%= csrf_meta_tags %>
</head>
<body>

	<div class="header">
		<h1 class="mainHeading">This will display the todos</h1>
	</div>
	<div class = "todoContent">
		<list-of-todo></list-of-todo>
	</div>
	
		
	
		
	
	
	
	
  	<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/todos/edit.html.erb
<%= form_for(@todo) do |f|%>
	<div>
	<%= f.label :done%>
	<%= f.check_box :done%>	
	</div>
	<div>
  <%= f.label :title%>
  <%= f.text_field :title%>
  </div>
  <div>
  <%= f.label :description%>
  <%= f.text_area :description%>
  </div>
  <%= f.submit "Update"%>
  <%= link_to "Back", todos_path%>
<% end %>

app/views/todos/index.html.erb
<h1>ToDo</h1>
<% if @todos.empty? %>
<p>No Todos</p>
<% end %>
<table>
	<thead>
		<tr>
			<th>Done</th>
			<th>Title</th>
			<th colspan="6"></th>
		</tr>
	</thead>
	
	<tbody>
		<%@todos.each do |todo| %>
			<tr>
				<td><%= todo.done %></td>
				<td><%= todo.title %></td>
				<td><%= link_to "Show", todo_path(todo)%></td>
				<td><%= link_to "Edit", edit_todo_path(todo)%></td>
				<td><%= link_to "Delete", todo, method: :delete, data: {confirm: "Are you sure?"}%></td>

			</tr>
		<% end %>
	</tbody>
</table>

<%= button_to('Create new ToDo', new_todo_path, method: "get") %>
<%= button_to('Delete all done', { :controller => :todos, :action => 'destroy_all_done' }, method: :delete) %>
<%= button_to('Delete all ToDo\'s', { :controller => :todos, :action => 'destroy_all' }, method: :delete) %>

app/views/todos/new.html.erb
<%= form_for(@todo) do |f|%>
<% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
  <%= f.label :title%>
  <%= f.text_field :title%>
  </div>
  <div>
  <%= f.label :description%>
  <%= f.text_area :description%>
  </div>
  <%= f.submit "Create todo"%>
<% end %>

app/views/todos/show.html.erb
<table cellspacing="10">
	<thead>
		<th>Done?</th>
		<th>Title</th>
		<th>Description</th>
		
	</thead>
	<tbody>
		<td><%= @todo.done %></td>
		<td><%= @todo.title%></td>
		<td><%= @todo.description%></td>
	</tbody>
</table>
<%= link_to "Edit", edit_todo_path%>
<%= link_to "Back", todos_path%>